name: naturalis_prinseq_sequence_trimmer
owner:  duijker.d
description: "trim/filter on length/quality or use to convert fastq to fasta." 
long_description: |
  "trim/filter on length/quality or use to convert fastq to fasta.".
remote_repository_url: https://github.com/naturalis/galaxy-tool-prinseq-sequence-trimmer.git
homepage_url: https://github.com/naturalis/galaxy-tool-prinseq-sequence-trimmer.git
type: unrestricted
categories:
   - "Fastq Manipulation - Tools for manipulating fastq data"
   - "Fasta Manipulation - Tools for manipulating fasta data"
auto_tool_repositories:
  name_template: naturalis_prinseq_sequence_trimmer
  description_template: naturalis_prinseq_sequence_trimmer